services:
  cma-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cma-middleware
    restart: unless-stopped
    ports:
      - "8555:8555"
    volumes:
      - ./api_gateway.db:/app/api_gateway.db
    env_file:
      - .env
