services:
  cma-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cma-middleware
    restart: unless-stopped
    ports:
      - "8555:8555"
    volumes:
      - ./api_gateway.db:/app/api_gateway.db
    env_file:
      - .env
    networks:
      - cma_net

networks:
  cma_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.200.3.0/24
